version: '3.3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'test-person'
      MYSQL_ROOT_PASSWORD: 'admin'
      TZ: 'America/Sao_Paulo'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: